name: Deploy Hexo website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          sudo npm install -g hexo-cli
          npm install

      - name: Build website
        run: hexo generate

      - name: Move website to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 13.233.61.113
          username: root
          password : qeM_f2SweF
          source: public/
          target: /home/deployment/
      
          

      - name: Run Deployment Script on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.61.113
          username: root
          password: qeM_f2SweF
          script: sudo sh /home/deployment/deployment.sh
